/*
 * ManagerDemoJFrame.java
 *
 * Created on 2008年8月7日, 上午2:31
 */

package net.epsilony.util.ui.interactive.demo;

import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.util.Random;
import javax.swing.JPanel;
import net.epsilony.util.ui.Model2D.CubicCurve2DElement;
import net.epsilony.util.ui.Model2D.Element2DManager;
import net.epsilony.util.ui.interactive.SelectFilters;

/**
 *
 * @author  epsilon
 */
public class ManagerDemoJFrame extends javax.swing.JFrame {

    /** Creates new form ManagerDemoJFrame */

    public ManagerDemoJFrame() {
        initComponents();
        manager=new Element2DManager(modelPanel);
        managerMouseAdapter=manager.getMouseAdapter();
        Random r= new Random();
        double w=modelPanel.getWidth();
        double h=modelPanel.getHeight();
        for(int i=0;i<20;i++){
            manager.elementsAdd(new CubicCurve2DElement(w*r.nextDouble(),h*r.nextDouble(),w*r.nextDouble(),h*r.nextDouble(),w*r.nextDouble(),h*r.nextDouble(),w*r.nextDouble(),h*r.nextDouble()));
        
        }//even upto 10000 it still works when selecting
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modelPanel = new ModelPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        modelPanel.setBackground(java.awt.Color.white);
        modelPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modelPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modelPanelMouseExited(evt);
            }
        });
        modelPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modelPanelMouseMoved(evt);
            }
        });
        modelPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                modelPanelPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(modelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    manager.createElement("CubicCurve");
}//GEN-LAST:event_jButton1ActionPerformed

private void modelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelPanelMouseClicked
// TODO add your handling code here:
    managerMouseAdapter.mouseClicked(evt);
}//GEN-LAST:event_modelPanelMouseClicked

private void modelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelPanelMouseExited
// TODO add your handling code here:
    managerMouseAdapter.mouseExited(evt);
}//GEN-LAST:event_modelPanelMouseExited

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    manager.selectElements(SelectFilters.getTypeFilter("CubicCurve2DElement"));
}//GEN-LAST:event_jButton2ActionPerformed

private void modelPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelPanelMouseMoved
// TODO add your handling code here:
    managerMouseAdapter.mouseMoved(evt);
}//GEN-LAST:event_modelPanelMouseMoved

private void modelPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_modelPanelPropertyChange
// TODO add your handling code here:
    System.out.println(evt.getPropertyName()+"  "+evt.getNewValue());
}//GEN-LAST:event_modelPanelPropertyChange

private void modelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelPanelMouseEntered
// TODO add your handling code here:
    managerMouseAdapter.mouseEntered(evt);
}//GEN-LAST:event_modelPanelMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDemoJFrame().setVisible(true);
            }
        });
    }

    class ModelPanel extends JPanel{

        @Override
        protected void paintComponent(Graphics arg0) {
            super.paintComponent(arg0);
            manager.paint(arg0);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel modelPanel;
    // End of variables declaration//GEN-END:variables

        
    Element2DManager manager=null;
    MouseAdapter managerMouseAdapter= null;
}
