/*
 * FourBezierCoordinateChange2DDemo.java
 *
 * Created on 2008年8月26日, 下午8:50
 */
package net.epsilony.math.temptest;

import net.epsilony.math.util.FourBezierCoordinateChange2D;
import java.awt.Color;
import net.epsilony.math.util.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.GeneralPath;
import java.awt.geom.Path2D;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author  epsilon
 */
public class FourBezierCoordinateChange2DDemo extends javax.swing.JFrame {

    /** Creates new form FourBezierCoordinateChange2DDemo */
    public FourBezierCoordinateChange2DDemo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new DemoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        FourBezierCoordinateChange2DDemo j= new FourBezierCoordinateChange2DDemo();
        j.demo();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            @Override
//            public void run() {
//                new FourBezierCoordinateChange2DDemo().setVisible(true);
//            }
//        });
    }
    
    public void demo() throws Exception{
        Path2D path = new GeneralPath.Double();
        path.moveTo(0, 0);
        path.quadTo(0, 45,0,90);
        path.curveTo(30,90,60,90,90,90);
        path.lineTo(90, 0);
        path.closePath();
        Shape s = path.createTransformedShape(AffineTransform.getTranslateInstance(100, 100));
        FourBezierCoordinateChange2D f = new FourBezierCoordinateChange2D(s);
        
        double[] results = new double[3];
        int n = 1000;
        double size = 1.0 / n;
        Date d=new Date();
        for (int i = 0; i <=n; i++) {
            for (int j = 0; j <=n; j++) {
                f.setup(s);
                f.getResults(i*size, j*size, results);
//                gr.draw(new PointMark2D(results[0], results[1],Math.sqrt(results[2])*size*size, "r"));
            }
            if(i%100==0){
                System.out.println("i:"+i);
            }
        }

        Date d2=new Date();
        System.out.println("time"+(d2.getTime()-d.getTime())/1000);
    }

    public void demoPaint(Graphics2D gr) throws Exception {
        Path2D path = new GeneralPath.Double();
        path.moveTo(0, 0);
        path.quadTo(0, 45,0,90);
        path.curveTo(30,90,60,90,90,90);
        path.lineTo(90, 0);
        path.closePath();
        Shape s = path.createTransformedShape(AffineTransform.getTranslateInstance(100, 100));
        FourBezierCoordinateChange2D f = new FourBezierCoordinateChange2D(s);
        gr.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        double[] results = new double[3];
        
        
        int n = 3000;
        double size = 1.0 / n;
        gr.setColor(Color.RED);
        Date d=new Date();
        for (int i = 0; i <=n; i++) {
            for (int j = 0; j <=n; j++) {
                f.setup(s);
                f.getResults(i*size, j*size, results);
//                gr.draw(new PointMark2D(results[0], results[1],Math.sqrt(results[2])*size*size, "r"));
            }
            if(i%100==0){
                System.out.println("i:"+i);
            }
        }
        Date d2=new Date();
        System.out.println("time"+(d2.getTime()-d.getTime())/1000);
        gr.setColor(Color.BLACK);
        gr.draw(s);
    }
    
        class DemoPanel extends JPanel {

            @Override
            protected void paintComponent(Graphics arg0) {
                super.paintComponent(arg0);
            try {

                demoPaint((Graphics2D) arg0);
            } catch (Exception ex) {
                Logger.getLogger(FourBezierCoordinateChange2DDemo.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
